- server.js
trying to make integration tests work on Travis
should be a temporary fix until I make it use postgres instead.
> making sure it uses the correct database

- tests/models/Activity.test.js
- tests/models/Document.test.js
- tests/models/Note.test.js
- tests/models/Publication.test.js
- tests/models/Reader.test.js
As it turns out, the problem was not with the code but with the tests. I completely messed up the creation of publications, documents and notes in my models tests. Somehow the tests were still passing. :woman_facepalming:
> fixed creation of publications, documents and notes in tests

- models/Publications_Tags.js
- routes/outbox-post.js
- tests/integration/tag.test.js
- tests/models/Publication.test.js
- tests/unit/post-outbox-route.test.js
This was suspiciously easy. I feel like I must have missed something.
> Remove tag from publication

- routes/activities/add.js
- routes/activities/delete.js
- routes/activities/remove.js
- routes/outbox-post.js
- tests/integration/note.test.js
- tests/integration/publication.test.js
- tests/integration/tag.test.js
- tests/unit/post-outbox-route-add.test.js
- tests/unit/post-outbox-route-delete.test.js
- tests/unit/post-outbox-route-remove.test.js
As it was some activities returned a 201 status and others a 204. I have made it 201 everywhere.
> fix status codes for activities

- models/Note.js
Turns out that when updating we also need to be able to update the summary for the text
> Make sure note summary property gets updated

- models/BaseModel.js
Make sure it doesn't store stuff it doesn't have to.
> Fix BaseModel json property

- migrations/20190409155349_reader.js
- migrations/20190409155848_publication.js
- migrations/20190409160155_document.js
- migrations/20190409160623_note.js
- migrations/20190409161058_tag.js
- migrations/20190409161233_attribution.js
- migrations/20190409162023_activity.js
- migrations/20190410091456_readActivity.js
- migrations/20190410092014_publication_tag.js
- migrations/20190410092110_note_tag.js
Created new migration files to replace the old ones. 
I tested that the migration works. But everything else should be broken by now.
> new migration files

- migrations/20190409155848_publication.js
- migrations/20190409160155_document.js
- migrations/20190409160623_note.js
- migrations/20190409161233_attribution.js
- migrations/20190410091456_readActivity.js
- migrations/20190410092014_publication_tag.js
- models/BaseModel.js
- models/Publication.js
- models/Reader.js
- models/utils.js
- package-lock.json
- package.json
- tests/models/Publication.test.js
- tests/models/index.js
That one was complicated.
I also noticed that in previous models, I had removed the url property, but I hadn't changed the id to be a url.
There's still some things to sort out with that (a lot of Base Model could still be removed)
I haven't implemented Attributions or Tag-Publication links yet.
> implemented changes to publication

- models/Activity.js
- models/Attribution.js
- models/BaseModel.js
- models/Document.js
- models/Note.js
- models/Publication.js
- models/Publications_Tags.js
- models/Reader.js
- models/utils.js
- package-lock.json
- routes/activities/delete.js
- routes/activities/read.js
- routes/utils.js
- tests/google-integration/file-upload.test.js
- tests/models/Activity.test.js
- tests/models/Attribution.test.js
- tests/models/Document.test.js
- tests/models/Note.test.js
- tests/models/Publication.test.js
- tests/models/Reader.test.js
- tests/models/index.js
I updated the activity model.
Then started doing a 'quick fix' that would make sure that database ids are not urls, but ids received by users are. 
Turns out that 'quick fix' was a bit of a pain. :woman_facepalming:
> Update activity model + fix Ids

- migrations/20190409161058_tag.js
- migrations/20190410092014_publication_tag.js
- migrations/20190410092110_note_tag.js
- models/Activity.js
- models/Attribution.js
- models/BaseModel.js
- models/Document.js
- models/Note.js
- models/Publication.js
- models/Reader.js
- models/utils.js
- tests/models/Note.test.js
I consolidated the creation of id, published and updated in the BaseModel. 
That means I also had to change the ids for Tags (which were integers. Everything else uses strings)
> Cleanup base model1

- models/Activity.js
- models/Attribution.js
- models/BaseModel.js
- models/Note.js
- models/Publication.js
- models/Reader.js
- routes/activities/create.js
- routes/activities/utils.js
- routes/outbox-post.js
- routes/publication.js
- tests/integration/index.js
- tests/integration/publication.test.js
- tests/integration/utils.js
This fixes creating a publication, getting a publication.
This does not fix getting read activity with publication. 
also the way it handles attributions is not very good, especially if we need to support a large number of different roles (currently only supports author and editor)
> fixed publication routes

- models/Attribution.js
- models/Publication.js
- routes/publication.js
- routes/user-library.js
- tests/integration/index.js
- tests/integration/library.test.js
- tests/integration/publication.test.js
I fixed the library route, except for filtering it by collection. Once the tags are fixed I will fix that.
I also cleaned up some of the mess regarding attributions.
> fixed library route and attributions

- models/Document.js
- models/Note.js
- routes/activities/create.js
- routes/activities/update.js
- routes/note.js
- routes/utils.js
- tests/integration/index.js
- tests/integration/note.test.js
fixes notes routes
when creating a note, expects a inReplyTo equal to the complete url of the document (e.g.: `http://server.com/publication-123/path/to/file`
When fetching a note, will return the same.
> fixed notes

- models/BaseModel.js
- models/Reader.js
- tests/integration/reader.test.js
- tests/models/Reader.test.js
- tests/unit/readers-route.test.js
I will be doing the same thing with publications, notes, tags, etc. I am making sure that the code, tests and documentation are consistent in regards to what the request and response objects should be. 
Note: I will be merging this as soon as the tests pass .
> clean up reader

- README.md
- doc.json
- docs/index.html
- routes/activities/delete.js
- routes/activity.js
- routes/publication.js
- routes/readers.js
- routes/user-library.js
- tests/integration/library.test.js
- tests/integration/publication.test.js
- tests/integration/reader.test.js
- tests/models/Attribution.test.js
- tests/models/Document.test.js
- tests/models/Publication.test.js
- tests/models/ReadActivity.test.js
- tests/performance/utils/createPublication.js
- tests/unit/post-outbox-route-delete.test.js
- tests/unit/post-outbox-route-remove.test.js
- tests/unit/publication-route.test.js
> fixed publications

- models/Reader.js
- package-lock.json
- package.json
- routes/activities/create.js
- routes/user-library.js
- tests/integration/index.js
- tests/integration/library.test.js
- tests/unit/user-library-route.test.js
I also added some missing tests (and fixed uncaught bug) related to filtering by tag.
I will look at this again again tomorrow morning, but so far seems to work.
library route accepts queries like: `limit=20&page=3` 
limit defaults to 10 and cannot be lower than 10 or higher than 100.
> Paginate library

- routes/outbox-get.js
@Marie000 Only few changes added. Please review my code!
> Change few variable names in outbox-get

- doc.json
- docs/index.html
- models/Reader.js
- routes/reader-notes.js
- tests/integration/reader-notes.test.js
- tests/performance/createNotes.test.js
- tests/performance/index.js
New query params:
orderBy - can be either 'created' or 'updated'. By default returns newest first.
reverse - if true, will return oldest first.
> Notes order by

- models/Attribution.js
- models/Document.js
- models/Publication.js
- models/Publications_Tags.js
- tests/integration/publication.test.js
- tests/models/Document.test.js
- tests/models/Publication.test.js
- tests/models/index.js
> Delete docs of pub2

- activityDoc.md
> Add delete to docu

- models/Note.js
- models/Publication.js
- models/ReadActivity.js
- models/Reader.js
- models/Tag.js
- routes/activities/create.js
- routes/activities/read.js
- routes/activities/update.js
- routes/middleware/error-handling.js
- routes/readers.js
- server.js
- tests/integration/activity-get.test.js
- tests/integration/index.js
- tests/integration/library-filter.test.js
- tests/integration/note-create.test.js
- tests/integration/note-update.test.js
- tests/integration/outbox-get.test.js
- tests/integration/publication-create.test.js
- tests/integration/readActivity-create.test.js
- tests/integration/reader-create.test.js
- tests/integration/tag-create.test.js
Now returning validation errors on create. 
I tried to make it work on updates, but so far no luck. I am not getting a ValidationError on updates for some reason.
> Input validation

- models/Note.js
- models/Publication.js
- package-lock.json
- package.json
- routes/activities/create.js
- routes/activities/update.js
- routes/middleware/error-handling.js
- tests/integration/index.js
- tests/integration/note-update.test.js
- tests/integration/publication-update.test.js
Well, I found a fix for the update validation problem. It works when I do a patch instead of an update. No idea why, but I can live with that. 
I also updated to the latest version of objection.js. It might have helped. Or at least it could help with my other database problems.
> fixed update validation

- models/Reader.js
- routes/middleware/error-handling.js
- routes/reader-library.js
- tests/integration/library-filter.test.js
I fixed library filters, at least partially.
You can now combine filters for:
- author and title
- attribution and title
- attribution, role and title
You still cannot combine author and attribution. That is more complicated to implement. And maybe less important?
> Fix library filters

- models/Publication.js
- routes/publication.js
- tests/integration/publication-get.test.js
Turned out to be a pretty simple fix.
> Pub with position

- routes/reader-notes.js
I forgot to update the doc for GET /reader-:id/notes
> updated doc

- models/Note.js
- models/Publication.js
- routes/activities/delete.js
- tests/integration/note-delete.test.js
- tests/models/Publication.test.js
Here is what the request to delete all notes for a publication looks like:
```
{
'@context': [
'https://www.w3.org/ns/activitystreams',
{ reader: 'https://rebus.foundation/ns/reader' }
],
type: 'Delete',
object: {
type: 'Collection',
name: 'Publication Notes',
id: publicationUrl
}
}
```
I can also change it if you think of a better way to do this.
> Delete notes for pub

- models/Tag.js
- routes/activities/update.js
- tests/integration/auth-error.test.js
- tests/integration/index.js
- tests/integration/library-filter.test.js
- tests/integration/library-get.test.js
- tests/integration/note-create.test.js
- tests/integration/note-delete.test.js
- tests/integration/note-get.test.js
- tests/integration/note-update.test.js
- tests/integration/publication-delete.test.js
- tests/integration/readerNotes-filter.test.js
- tests/integration/readerNotes-get.test.js
- tests/integration/readerNotes-orderBy.test.js
- tests/integration/readerNotes-paginate.test.js
- tests/integration/tag-delete.test.js
- tests/integration/tag-note.test.js
- tests/integration/tag-publication.test.js
- tests/integration/tag-update.test.js
- tests/utils/utils.js
I added an update Tag feature. It makes it possible to update the name or the json on a tag. 
While I was at it, I started cleaning up some tests. So that's why this pull request is much bigger than it should be. 
So this is the important part, what a request to update a tag should look like: 
```
const res = await request(app)
.post(`${readerUrl}/activity`)
.set('Host', 'reader-api.test')
.set('Authorization', `Bearer ${token}`)
.type(
'application/ld+json; profile="https://www.w3.org/ns/activitystreams"'
)
.send(
JSON.stringify({
'@context': [
'https://www.w3.org/ns/activitystreams',
{ reader: 'https://rebus.foundation/ns/reader' }
],
type: 'Update',
object: {
type: 'reader:Tag',
id: stack.id,
name: 'newName'
}
})
)
```
> update Tag + cleaning up tests

- models/Reader.js
Those are the places I found that could cause ambiguity re: which 'updated' column it was referring to. 
That might fix your bug?
> removed some ambiguity in updated column

- models/Publications_Tags.js
- tests/models/Publication.test.js
just adding a model method that will be needed for searching by collection. (will do the rest of search by collection in a different pull request once all is merged)
> added getIdsByCollection method

- .travis.yml
- dev.js
- models/Publication.js
- package-lock.json
- package.json
- routes/publication-file-upload.js
- routes/search.js
- server.js
- tests/google-integration/index.js
- tests/google-integration/publication-file-upload.test.js
- tests/google-integration/search.test.js
- tests/test-files/file1.html
- tests/test-files/file2.html
- tests/test-files/file3.html
- tests/test-files/file4.html
- utils/queue.js
fyi @baldurbjarnason 
still a bit of work to be done, but overall, it works. 
The biggest problem with it right now is that it slows down uploading documents. 
We will also need to add environment variables. 
will let you know when this is ready to be reviewed.
> Full text search

- routes/publication-file-upload.js
- tests/google-integration/search.test.js
- utils/queue.js
and making sure the build works on a pull request too.
> fixing debugging mess I created on master

- routes/job-patch.js
so the google function does not have any auth token, so I am removing the authentication on the patch /job-{id} endpoint. 
Hopefully that wont cause much problems. If it does, we'll have to think of some other solution
> remove auth

- processFiles/saveFiles.js
> fixing file

- models/Attribution.js
- models/Publication.js
- routes/activities/create.js
- routes/publication-post.js
- server.js
- tests/integration/auth-error.test.js
- tests/integration/index.js
- tests/integration/publication-post.test.js
- tests/models/Attribution.test.js
So the route works now. 
Note that there is no validation going on for properties that go into the metadata object. We might want to add that later.
Other validation errors should work. I'll have to think if there is anything else I should test.
> New create pub route

- models/Publication.js
- routes/activities/update.js
- routes/publication-post.js
- tests/integration/library-get.test.js
- tests/integration/publication-delete.test.js
- tests/integration/publication-get.test.js
- tests/integration/publication-post.test.js
- tests/integration/publication-update.test.js
- tests/models/Attribution.test.js
- tests/models/Document.test.js
- tests/models/Note.test.js
- tests/models/Publication.test.js
- tests/models/ReadActivity.test.js
- tests/models/Tag.test.js
- tests/performance/utils/createPublication.js
- tests/utils/utils.js
adds validation to both create property and update property
> Add validation

- routes/publication-delete.js
- routes/publication-patch.js
- routes/publication-post.js
- server.js
- tests/integration/auth-error.test.js
- tests/integration/index.js
- tests/integration/publication-delete-old.test.js
- tests/integration/publication-delete.test.js
- tests/utils/utils.js
endpoint:
DELETE /readers/:readerId/publications/:pubId
returns 204 status
that's pretty much it.
> Delete pub endpoint

- routes/publication-get.js
- server.js
- tests/integration/auth-error.test.js
- tests/integration/note-delete.test.js
- tests/integration/note-get.test.js
- tests/integration/publication-delete-old.test.js
- tests/integration/publication-delete.test.js
- tests/integration/publication-get.test.js
- tests/integration/publication-tag.test.js
- tests/integration/publication-update.test.js
- tests/integration/tag-publication.test.js
GET /publications/:pubId
I left the old endpoint there for now, but it is no longer tested, so there is no guarantee that future changes will not break it.
> Get publication

- models/Tag.js
- routes/activities/create.js
- routes/tag-delete.js
- routes/tag-patch.js
- routes/tag-post.js
- server.js
- tests/google-integration/search.test.js
- tests/integration/auth-error.test.js
- tests/integration/index.js
- tests/integration/library-filter-collection.test.js
- tests/integration/library-filter-combined.test.js
- tests/integration/library-filter-old.test.js
- tests/integration/publication-tag.test.js
- tests/integration/readerNotes-filter.test.js
- tests/integration/tag-delete-old.test.js
- tests/integration/tag-delete.test.js
- tests/integration/tag-note.test.js
- tests/integration/tag-patch.test.js
- tests/integration/tag-post.test.js
- tests/integration/tag-publication.test.js
- tests/models/Tag.test.js
- tests/utils/utils.js
Adding 3 new endpoints:
POST /tags
PATCH /tags/:tagId
DELETE /tags/:tagId
> Tag endpoints

- models/Publication.js
- models/Reader.js
- routes/reader-library.js
- tests/integration/deprecated/publication-update.test.js
- tests/integration/index.js
- tests/integration/library/library-filter-combined.test.js
- tests/integration/library/library-filter-keyword.test.js
- tests/integration/library/library-filter-title.test.js
- tests/integration/library/library-filter-type.test.js
- tests/integration/library/library-orderBy-datePublished.test.js
- tests/integration/library/library-orderBy-default.test.js
- tests/integration/library/library-orderBy-title.test.js
- tests/integration/publication/publication-delete.test.js
- tests/integration/publication/publication-get.test.js
- tests/integration/publication/publication-patch.test.js
- tests/integration/publication/publication-post.test.js
- tests/integration/tag/tag-create.test.js
- tests/integration/tag/tag-delete.test.js
- tests/integration/tag/tag-patch.test.js
- tests/integration/tag/tag-post.test.js
e.g. GET /readers/:readerId/library?keyword=something
not case sensitive
also now all keywords are stored as lowercase
> Filter library by keyword

- models/Reader.js
- routes/reader-library.js
- tests/integration/index.js
- tests/integration/library/library-filter-combined.test.js
- tests/integration/library/library-filter-search.test.js
new filter for the library
e.g.
GET /readers/:id/library?search=something
it searches through the title, description, abstract and keywords. 
later we might want to give the option to search some of those fields, but for now I think this will do.
> Search library

- -cov
- models/Note.js
- package.json
- routes/note-post.js
- server.js
- tests/integration/auth/forbidden.test.js
- tests/integration/auth/unauthorized.test.js
- tests/integration/deprecated/tag-delete-old.test.js
- tests/integration/deprecated/tag-note.test.js
- tests/integration/deprecated/tag-update.test.js
- tests/integration/index.js
- tests/integration/note/note-post.test.js
- tests/integration/tag/tag-delete.test.js
- tests/integration/tag/tag-note-delete.test.js
- tests/integration/tag/tag-note-put.test.js
- tests/integration/tag/tag-patch.test.js
- tests/models/Note.test.js
- tests/models/NoteBody.test.js
- tests/models/Publication.test.js
- tests/utils/testUtils.js
new endpoint:
POST /notes
the body it expects follows the new Notes Model. 
This breaks the other notes endpoints. I will fix them one by one.
> Post notes endpoint

- routes/note-delete.js
- server.js
- tests/integration/auth/forbidden.test.js
- tests/integration/auth/unauthorized.test.js
- tests/integration/index.js
- tests/integration/note/note-delete.test.js
new endpoint:
DELETE /notes/:noteId
not much else to say about it. Pretty straightforward.
> delete note endpoint seems to work

- migrations/20200212130857_NoteRelation.js
- models/Note.js
- models/NoteContext.js
- models/NoteRelation.js
- routes/noteContext-get.js
- routes/noteRelation-post.js
- server.js
- tests/integration/auth/forbidden.test.js
- tests/integration/auth/unauthorized.test.js
- tests/integration/index.js
- tests/integration/note/note-get.test.js
- tests/integration/noteContext/noteContext-get.test.js
- tests/models/NoteRelation.test.js
- tests/utils/testUtils.js
new route:
GET /noteContexts/:id
This will return the noteContext object with notes. Notes will each have their relations and body.
> get NoteContext with notes and noteRelations

- models/BaseModel.js
- models/NoteContext.js
- tests/integration/index.js
- tests/integration/noteContext/noteContext-addNote.test.js
- tests/integration/noteContext/noteContext-delete.test.js
- tests/integration/noteContext/noteContext-get.test.js
- tests/integration/noteContext/noteContext-put.test.js
The id for NoteContext is now a url
I also added more tests.
> Context fixes

- migrations/20190409155849_notebook.js
- migrations/20190409160622_NoteContext.js
- migrations/20200504135759_notebook_tag.js
- migrations/20200504135932_notebook_pub.js
- migrations/20200505093835_notebook_note.js
- models/Notebook.js
- models/Notebook_Note.js
- models/Notebook_Pub.js
- models/Notebook_Tag.js
- package.json
- tests/models/Notebook.test.js
- tests/models/Notebook_Note.test.js
- tests/models/Notebook_Pub.test.js
- tests/models/Notebook_Tag.test.js
- tests/models/index.js
This creates database tables for:
- notebook
- notebook_tag relation
- notebook_pub relation
- notebook_note relation
I also created the models for those tables with some very basic methods. 
Eventually we might want to add some more information to things like notebook_pub relation and notebook_note relation. We can decide that later.
> Create notebook object

- models/Notebook.js
- routes/notebook-post.js
- routes/swagger-definitions/outline-def.js
- server.js
- tests/integration/auth/unauthorized.test.js
- tests/integration/index.js
- tests/integration/notebook/notebook-post.test.js
- tests/models/Notebook.test.js
- tests/models/Notebook_Note.test.js
- tests/models/Notebook_Pub.test.js
- tests/models/Notebook_Tag.test.js
POST /notebooks endpoint.
Notebook object:
name: string  - required
description: string
status: string - can be either 'active' or 'archived'. Defaults to 'active' if not specified
settings: object - currently doesn't have an opinion about what is in the object. That might change later
returns 201 status and created notebook object
> Post notebook

- models/Notebook.js
- routes/notebook-delete.js
- routes/notebook-put.js
- server.js
- tests/integration/auth/forbidden.test.js
- tests/integration/auth/unauthorized.test.js
- tests/integration/index.js
- tests/integration/notebook/notebook-delete.test.js
- tests/integration/notebook/notebook-put.test.js
- tests/models/Notebook.test.js
Two new enpoints:
PUT /notebooks/:id
DELETE /notebooks/:id
works as usual. Delete is a soft delete. Put returns the updated object.
> Put and Delete Notebook

- models/Note.js
- models/Notebook.js
- models/Notebook_Note.js
- routes/notebooks/notebook-delete-note.js
- routes/notebooks/notebook-note-post.js
- routes/notebooks/notebook-put-note.js
- server.js
- tests/integration/auth/forbidden.test.js
- tests/integration/auth/unauthorized.test.js
- tests/integration/index.js
- tests/integration/notebook/notebook-get.test.js
- tests/integration/notebook/notebook-note-delete.test.js
- tests/integration/notebook/notebook-note-post.test.js
- tests/integration/notebook/notebook-note-put.test.js
- tests/models/Notebook_Note.test.js
- tests/utils/testUtils.js
Three new routes:
PUT /notebooks/:id/notes/:noteId
to create a relation between a note and a notebook
DELETE /notebooks/:id/notes/:noteId
to remove the relation
POST /notebooks/:id/notes
with a note as a body
to create a note that will be assigned to the notebook. So it is the equivalent of calling
- POST /notes
and then
- PUT /notebooks/:id/notes/:noteId
> Notebook note

- migrations/20190409160600_canvas.js
- models/Canvas.js
- tests/models/Canvas.test.js
- tests/models/index.js
Added canvas object in database, and a canvasId to the noteContext. 
I left the notebookId in the noteContext, even if it's not strictly necessary anymore, since canvas has a notebookId. But it should make it easier to sort noteContexts. Also, I am not 100% convinced about the concept of canvas and just in case, this will make it easier to go back to just noteContexts. 
I also created a basic model for the Canvas objects. The rest will come later when I get around to creating the endpoints.
> Canvas Object

- models/readerNotes.js
- routes/notes/readerNotes-get.js
- tests/integration/readerNotes/readerNotes-filter-collection.test.js
- tests/integration/readerNotes/readerNotes-filter-flag.test.js
- tests/integration/readerNotes/readerNotes-filter-tag.test.js
Now accepts multiple queries for 'tag', 'flag' and 'stack'
E.g.: 
GET /notes?flag=important&flag=urgent
This will return a list of note that have both flags
> Query with multiple tags

- index.js
Pretty sure this is the only change that's required
> Update index.js to not nuke the DB on start

- models/BaseModel.js
- models/library.js
- models/readerNotes.js
- tests/integration/hardDelete/deleteNotebook.test.js
- tests/integration/hardDelete/deleteTag.test.js
- tests/integration/notebook/notebook-get.test.js
- tests/models/Canvas.test.js
- tests/models/Tag.test.js
cleans up the code for the library and notes filter. Should have no impact on users
I also changed the id for notebooks so that it is now a url. It should have always been like that but I somehow forgot.
> Filter refactor

- routes/notes/note-post.js
- routes/sources/source-post.js
- routes/tags/tag-delete.js
- routes/tags/tag-post.js
- routes/tags/tag-put.js
- routes/tags/tags-get.js
- tests/integration/tag/tags-get.test.js
- utils/cache.js
cache for the GET /tags endpoint
It resents when a tag is created, updated or deleted. Also when a tag is created at the same time as a source or note.
> Tags cache

- routes/notebooks/notebook-delete-note.js
- routes/notebooks/notebook-delete-source.js
- routes/notebooks/notebook-delete-tag.js
- routes/notebooks/notebook-delete.js
- routes/notebooks/notebook-note-post.js
- routes/notebooks/notebook-post.js
- routes/notebooks/notebook-put-note.js
- routes/notebooks/notebook-put-source.js
- routes/notebooks/notebook-put-tag.js
- routes/notebooks/notebook-put.js
- routes/notebooks/notebook-source-post.js
- routes/notebooks/notebooks.get.js
- routes/notes/note-delete-tag.js
- routes/notes/note-delete.js
- routes/notes/note-post.js
- routes/notes/note-put-tag.js
- routes/notes/note-put.js
- routes/sources/source-batchUpdate.js
- routes/sources/source-delete-tag.js
- routes/sources/source-delete.js
- routes/sources/source-patch.js
- routes/sources/source-post.js
- routes/sources/source-put-tag.js
- routes/tags/tag-delete.js
- routes/tags/tag-post.js
- routes/tags/tag-put.js
- tests/integration/notebook/notebooks-get.test.js
- utils/cache.js
cache on the GET /notebooks
this cache resets any time:
a source, note, tag, notebook is created, updated or deleted
a source-tag, note-tag, notebook-tag, source-notebook, note-notebook link is created or updated.
So yeah... anything and everything resets that cache. Still better than no cache, I guess. :woman_shrugging:
> notebooks cache

- models/Notebook_Source.js
- models/Source.js
- routes/sources/source-patch.js
- routes/sources/source-post.js
- tests/integration/source/source-patch.test.js
- tests/integration/source/source-post.test.js
Same thing I just did with the notes, but with sources this time.
> Create and update source with notebooks

- routes/hardDelete.js
- tests/integration/auth/forbidden.test.js
- tests/integration/auth/unauthorized.test.js
- tests/integration/hardDelete/deleteCanvas.test.js
- tests/integration/index.js
Added hard delete for the canvas, with tests
Also added tests of authentication errors, which I forgot when I did the routes.
> Canvas hard delete and auth tests

- routes/canvas/canvas-delete.js
- routes/noteContexts/noteContext-delete.js
- routes/notebooks/notebook-delete.js
- routes/notes/note-delete.js
- routes/readers/reader-delete.js
- routes/sources/source-delete.js
- routes/tags/tag-delete.js
- routes/tags/tag-post.js
- tests/integration/note/note-delete.test.js
- utils/metrics.js
I added metrics:
createTag (tags of any type except 'stack')
createStack (tags of type 'stack')
createReader
createCanvas
deleteReader
deleteNotebook
deleteNoteContext
deleteNote
deleteSource
deleteCanvas
Now I realize I am missing deleteTag. I assume we will need this? This would encompass any type of tag, including stack. I cannot easily differentiate between types on the delete metrics.
> More metrics

- models/Canvas.js
- routes/canvas/canvas-getAll.js
- tests/integration/canvas/canvas-filter-notebook.test.js
- tests/integration/index.js
filter:
GET /canvas?notebook=notebook shortId
pretty straightforward.
Does not have pagination.
> filter canvas by notebook

- migrations/20210118095220_collaborator.js
- models/Collaborator.js
- tests/models/Collaborator.test.js
- tests/models/index.js
Created the collaborator table:
Collaborator object:
```
id: <string>
readerId: <string>
notebookId: <string>
permission: <object, with properties like {read: true, comment: true...}>
status: <string, but stored as an integer. Can be 'pending', 'accepted', 'refused', etc>
published: <timestamp>
updated: <timestamp>
deleted: <timestamp>
```
readerId, notebookId, permission and status are required
Initialll I was going to have a 'role' field to differentiate between owner and collaborator, but we don't need to store the owner here since it is the person who created the notebook. So unless we want people to eventually be able to change ownership of a notebook, we don't need it here. Other information can be stored in the permission object.
Makes sense?
> added collaborator table and model
