models/Publication.js, routes/outbox-post.js, tests/integration/publication.test.js, tests/models/Publication.test.js, tests/unit/post-outbox-route.test.js
This does a hard delete of the publication and all activities associated with the publication id.
This does not delete any documents or notes associated with that publication. 
It also does not delete any tag-publication join.
I don't think any of this will be a problem for now. 
One thing I wanted to do was return a 404 error if trying to delete a publication that does not exist. However, the way the post-outbox route is set up, that kind of thing is getting quite complicated. I will refactor this whole route. I will do that in another pull request to keep this one legible.
=> delete publiation implemented

doc.json, migrations/20190204095234_reader.js, migrations/20190204095305_publication.js, migrations/20190204095340_document.js, migrations/20190204095447_note.js, migrations/20190204095522_tag.js, migrations/20190204095603_activity.js, migrations/20190204095724_attribution.js, models/BaseModel.js, models/Note.js, models/Publication.js, routes/activities/delete.js, routes/document.js, routes/note.js, routes/publication.js, routes/user-library.js, tests/integration/auth-error.test.js, tests/integration/note.test.js, tests/integration/publication.test.js, tests/models/Note.test.js, tests/models/Publication.test.js, tests/unit/post-outbox-route-delete.test.js
Added a deleted timestamp, which will give us the option later on to set some sort of expiry. 
Delete works for publication and notes
I tested that the library does not return deleted publications
And Publications and Documents do not return deleted notes
Also trying to get a deleted publication or note directly will return a 404 error, of course.
=> soft delete of publication and note

models/Activity.js, models/Document.js, models/Publication.js, routes/activities/read.js, routes/activities/remove.js, routes/document.js, routes/outbox-post.js, routes/publication.js, tests/integration/document.test.js, tests/integration/publication.test.js, tests/integration/utils.js, tests/unit/post-outbox-route-read.test.js, tests/unit/publication-route.test.js
The implementation is similar to what we had discussed.
Some small changes:
In the request, the object is an object with a  type ('Document') and an id (document url). I could make it work with just the url, since I don't expect that read activity will ever apply to anything other than a document. But this was more consistent with how other activities are implemented. 
When getting a document, the response will include a position, which is a string
When getting a publication, the response will include a position, which is an object with a documentId (url) and a value (string)
Does that work for you?
=> Create read activity

activityDoc.md, models/Note.js, models/Publication.js, models/Publications_Tags.js, models/Reader.js, models/Tag.js, routes/activities/add.js, routes/activities/create.js, routes/activities/delete.js, routes/activities/read.js, routes/activities/remove.js, routes/activities/update.js, routes/outbox-post.js, tests/integration/auth-error.test.js, tests/integration/document.test.js, tests/integration/note.test.js, tests/integration/publication.test.js, tests/integration/tag.test.js, tests/integration/utils.js, tests/models/Document.test.js, tests/models/Note.test.js, tests/models/Publication.test.js, tests/unit/post-outbox-route-add.test.js, tests/unit/post-outbox-route-create.test.js, tests/unit/post-outbox-route-delete.test.js, tests/unit/post-outbox-route-read.test.js, tests/unit/post-outbox-route-remove.test.js, tests/unit/post-outbox-route-update.test.js
So swagger is doing a good job of documenting single-purpose endpoints, but with our POST /outbox endpoint handling so many different activities, it wasn't really clear. 
As a supplement to the swagger doc, I have created a simple .md file 
Later, I might want to use postman to document the example (which would have the added benefit of being testable, so we would know that the examples do work) but that seems complicated and it does repeat a lot of what swagger already does. 
By doing the documentation, I did notice that it wasn't really clear how creating a document for a publication worked. It was working if you specified the publicationId (the actual id that is in the database) but I fixed it so that using `context: publicationUrl` now works. Which makes more sense. (publicationId …
=> document POST activities endpoint

models/Tag.js, routes/activities/create.js, routes/activities/utils.js, routes/user-library.js, tests/integration/library.test.js, tests/integration/tag.test.js
I thought about filtering at the level of the database query,  but that is a little complicated since the query is for the reader. 
You can now request the library by adding `?stack=stackname` to the url. 
One small change: I have made it an error for a reader to create more than one stack with the same name. If we ever have other types of tags, the name can be reused for another type. 
In summary, when creating tags, the combination of readerId, name and type must be unique.
=> Filter library

knexfile.js
This makes knex.js find the migrations folder based on the relative path from the current module directory instead of the current working directory.
This makes the whole app more reusable as a module.
(As an experiment I'm testing using GitHub to edit and create pull requests for single file fixes. Let me know if it causes any weirdness. If this works nicely then it's an easy way to create pull requests for small, quick fixes.)
=> Updating knexfile.js

models/Publication.js
There is no reason for Publication#asRef to exist as the bandwidth savings are nonexistent and it causes a lot of problems as per https://github.com/RebusFoundation/reader-api/issues/79
I made it just return `this` to begin with but long term the right thing to do is just not use asRef
=> Making Publication#asRef return the full instance

models/BaseModel.js
Without this change Publication tags don't appear in the library stream.
I officially dislike the BaseModel.
=> Make sure Base Model doesn't strip tags from JSON

package.json, tests/integration/library.test.js, tests/performance/addPubToCollection.test.js, tests/performance/createDocuments.test.js, tests/performance/createNotes.test.js, tests/performance/createPublications.test.js, tests/performance/createTags.test.js, tests/performance/getDocumentWithNotes.test.js, tests/performance/getUserProfile.test.js, tests/performance/index.js, tests/performance/library.test.js, tests/performance/utils/createDocument.js, tests/performance/utils/createNotes.js, tests/performance/utils/createPublication.js, tests/performance/utils/createTags.js
There might be a better way to test for performance, but this can be useful to quickly test for problems. 
It is not complete, but it should be easy to add more tests or modify the existing ones as needed. 
Right now the test just logs times to the console. So it doesn't really indicate if the performance has changed since last time... but if we have doubt about any new changes, we can always do a before/after comparison. As long as we remember to test before. 
Some tests might be less than useful (who is going to create 100 notes at once?) but once the setup was done, adding more tests was really easy. :slightly_smiling_face: 
Eventually we can look into doing proper load tests on the api.
=> added performance tests

migrations/20190204095340_document.js, migrations/20190204095447_note.js, migrations/20190204100210_publications_tags.js, models/Note.js, models/Publications_Tags.js, models/Reader.js, routes/activities/remove.js, tests/integration/document.test.js, tests/integration/note.test.js, tests/integration/tag.test.js, tests/models/Note.test.js, tests/models/Publication.test.js, tests/unit/post-outbox-route-remove.test.js
This should improve the performance for:
- assigning a tag to a publication
- removing a tag from a publication
- creating notes
- creating documents
The goal here was to reduce back-and-forth communication between the api and the database. 
it removes checks for:
- creating notes for document that does not exist*
- creating notes for publication that does not exist*
- creating document for publication that does not exist*
- creating notes where the document and publication do not match**
- creating duplicate associations between tags and documents
(* will be reintroduced when we migrate the database)
(** might be able to reintroduce that one. Will also necessitate migration of database)
it maintains checks for:
- assigning a tag to a publication that does not exist
- assigning a tag that …
=> Simplify assign collection

models/Reader.js, models/Tag.js, tests/models/Publication.test.js, tests/models/Tag.test.js, tests/models/index.js
very few changes. Except that somehow I had two different ways of creating tags:
Reader.addTag
and
Tag.createTag
I kept the Tag.createTag. And I think I will move other similar methods to their own model. It's confusing to have them in Reader.
=> Update tag model

migrations/20190409161233_attribution.js, models/Attribution.js, models/Publication.js, tests/models/Attribution.test.js, tests/models/Publication.test.js, tests/models/index.js
For now accepts only roles of 'author' and 'editor'. I know we will need to accept a lot more roles, but that will be easy to expand later. I just wanted to make sure it all works.
@rabhiso There is one method I didn't implement yet: deleteByPublicationId
The reason why we need this is that updates to authors, editors, etc. will be done through updates to the publication. So when people update the list of authors for a publication, the easiest thing for use to do will be to delete all authors for that publication and create new ones. So actually, the method will need to delete all attributions for a particular publicationId and with a particular role ('author', 'editor'). Do you think you can do that? We will need to have tests for it too (in the /tests/models/Attribution.test.js file). …
=> Update attribution model

doc.json, docs/index.html, models/Reader.js, routes/activity.js, routes/readers.js, routes/user.js, routes/utils.js, routes/whoami.js, tests/integration/index.js, tests/integration/reader.test.js, tests/unit/readers-route.test.js, tests/unit/whoami-route.test.js
This fixes the following routes:
POST /readers
GET /reader-{id}
GET /whoami
Changes for the API users:
readers object can include 'profile', 'preferences' and 'json' objects.
when creating readers, no need to specify `type: 'Person'`. That is assumed.
no more stream objects returned
I think that's it.
=> fixed readers routes

models/Reader.js, routes/reader-library.js, tests/integration/library.test.js
new query parameters for the library route:
orderBy - can be either 'title' or 'datePublished'
reverse=true 
by default, datePublished will return most recent first. 
as discussed earlier, publications with no datePublished will be considered to be the oldest. 
They work with other filters and with pagination.
let me know if you ever want me to rename the parameters. For example I could use ascending / descending instead of reverse.
=> Library order by

activityDoc.md, doc.json, docs/index.html, models/Reader.js, models/Tag.js, routes/activities/add.js, routes/activities/create.js, routes/activities/delete.js, routes/activities/remove.js, routes/activity.js, routes/reader-library.js, tests/integration/activity-create.test.js, tests/integration/library-filter.test.js, tests/integration/note-delete.test.js, tests/integration/publication-delete.test.js, tests/integration/readerNotes-get.test.js, tests/integration/tag-create.test.js, tests/integration/tag-delete.test.js, tests/integration/tag-note.test.js, tests/integration/tag-publication.test.js, tests/models/Note.test.js, tests/models/Publication.test.js, tests/models/Tag.test.js, tests/performance/addPubToCollection.test.js, tests/performance/utils/createTags.js
Warning: this is a breaking change.
Before, tag objects had a property type equal to 'reader:Stack'
Now: 
{
type: 'reader:Tag',
tagType: 'reader:Stack' // or anything else
...
}
We are still enforcing uniqueness of tagType + name + readerId
When adding / removing a tag-note or tag-publication link, the object should be: 
{ 
type: 'reader:Tag'
id: tagId
}
no need to specify the tagType
Same for deleting a Tag (or updating a Tag, which is not yet implemented)
=> changed type of tags and added tagType

activityDoc.md, models/Note.js, routes/activities/create.js, tests/integration/note-create.test.js
That was a pretty quick fix.
So with these changes, notes attached to a document only need the document url in inReplyTo. They do not need a context. The publication id will be extracted from the inReplyTo. 
You can also create a note with only a context and no inReplyTo. Or with neither.
If you create a note with both a inReplyTo and a context, the context provided will overwrite the one  extracted from inReplyTo. It could also give an error if you prefer (but I guess that would be a breaking change for you if we do that).
=> creating note requires either a document url or a pubid, not both

models/Reader.js, routes/middleware/error-handling.js, routes/reader-library.js, tests/integration/library-filter.test.js, tests/utils/utils.js
This moves most of the filtering for library to after the database query. It is not ideal, but will eventually be fixed. 
For now, it means that filters work properly.
I also noticed that I was still filtering for collection and filtering out deleted publications after the database query, which would have caused problems with pagination. This fixes that.
=> Temporary fix for library filters

models/Note.js, models/Reader.js, tests/integration/readerNotes-get.test.js
changes for route /reader-:id/notes: each note will now have a .publication property which includes name, author, and other metadata.
=> loading reader notes now also includes publication information

models/Publication.js, models/Reader.js, routes/reader-library.js, routes/reader-notes.js, tests/integration/library-get.test.js, tests/integration/readerNotes-filter.test.js, tests/models/Publication.test.js
Finally managed to fix those database queries. :tada: 
From a user's perspective it shouldn't make much of a difference, except by possibly being more efficient.
What I changed:
all queries for the library are handled in a single database query. No more fetching everything and filtering after the fact.
I also made it so that it wont return deleted publications. (before the filtering out of deleted publication was done after the database query, which could mess up pagination)
the readerNotes route now has a 'stack' filter, just like the library. 
`/reader:-{id}/notes?stack=mycollection`
I have removed the publication.asRef method. It was only used for the library, so I changed the database query to only get the fields we want. The only change there that would be visible to the user is that …
=> Database queries fixed!

.travis.yml, doc.json, docs/index.html, models/Reader.js, routes/reader-library.js, routes/reader-notes.js, tests/integration/library-filter.test.js, tests/integration/library-paginate.test.js, tests/integration/readerNotes-filter.test.js, tests/integration/readerNotes-paginate.test.js
This is still a work in progress. It works for the library. I can do the same for the readerNotes, and eventually the activities.
But before I do, I want to make sure that this is something that is worth it. And that there isn't any obvious easier way that I didn't think of.
I tried using the knex-paginator package but that did not work, because the count / pagination I am doing is in a sub-query. What I am querying is the Reader table and then doing a whole mess of eager loading and joins with other tables. 
The solution I am doing right now is not ideal. There is a lot of repetition and any change to the filters will mean changes in two different complex queries. 
I did make it so that we don't have to call the query whenever we are on the last page (if the page limit is 10 and there …
=> Trying to fix totalItems

package-lock.json, package.json, tests/performance/load-tests/README.md, tests/performance/load-tests/index.js, tests/performance/load-tests/load-test.yml, tests/performance/load-tests/test.js
For now only tests getting the library. It could be extended to other endpoints later.
Also, running the load tests is not a single script. We need to:
run: `npm run before-test-load`
this will log a readerUrl and a token to the console. We need to copy and paste them in the script for 'test-load'
Then run `npm run test-load`
=> first load tests

routes/file-upload-pub.js, tests/getToken.js, tests/google-integration/index.js
actually what I was missing was the jobId. So now the name of the file uploaded will be:
reader-{readerId)/job-{jobId}/filename.epub
that way I can extract the readerId and jobId. The publicationId will be created by the google function. It will be in the job object once the job is done. 
makes sense?
(I know that right now I inverted the readerId and jobId... will push changes in a few minutes to fix that)
=> renamed the file to be uploaded

models/Publication.js, package-lock.json, package.json, routes/activities/add.js, routes/activities/create.js, routes/activities/delete.js, routes/activities/remove.js, routes/activities/update.js, routes/reader-library.js, server.js, tests/integration/library-get.test.js, utils/cache.js
This implements the if-modified-since header for the library route.
If the library has not been modified, it returns a 304 status
The library is considered modified by these actions:
- create publication
- update publication
- delete publication
- create tag
- update tag
- delete tag
- assign publication to tag
- remove publication from tag
I have set the cache data to expire after 100 seconds. I now realise that is quite short. It was useful for testing... but I will change that. Maybe an hour?
=> cache library

doc.json, docs/index.html, knexfile.js, migrations/20190409155848_publication.js, models/Publication.js, models/Reader.js, processFiles/saveFiles.js, routes/publication.js, routes/reader-library.js, tests/google-integration/search.test.js, tests/integration/library-filter.test.js, tests/integration/library-get.test.js, tests/integration/note-create.test.js, tests/integration/publication-delete.test.js, tests/integration/publication-get.test.js, tests/integration/publication-update.test.js, tests/integration/readActivity-create.test.js, tests/integration/readerNotes-get.test.js, tests/integration/readerNotes-orderBy.test.js, tests/integration/readerNotes-paginate.test.js, tests/integration/tag-publication.test.js, tests/models/Attribution.test.js, tests/models/Publication.test.js, tests/models/ReadActivity.test.js, tests/models/Tag.test.js, tests/performance/utils/createPublication.js, tests/utils/utils.js
So those are the new properties that have their own database column:
- abstract (replaces description)
- type 
- numberOfPages
- encodingFormat
I also made readingOrder optional. 'type' is now required. Which reminds me that I should add tests to make sure we handle missing type errors correctly. 
Aside from that I updated the tests, and I made sure that getting the publication and getting the library will also return the new properties.
=> Added propreties to Publication database table

models/Publication.js, routes/publication.js, routes/reader-library.js, tests/integration/library-filter.test.js, tests/integration/library-get.test.js, tests/integration/publication-get.test.js, tests/integration/publication-update.test.js, tests/models/Publication.test.js
This adds these properties to the metadata field:
- url
- dateModified
- bookEdition
- bookFormat
- isbn
- copyrightYear
- genre
- license
It also adds these attribution roles:
- contributor
- creator
- illustrator
- publisher
- translator
Those roles can also be used for filtering the library. For example:
GET /library?attribution=Smith&role=illustrator
=> Add metadata and attributions

routes/activities/update.js, routes/publication-patch.js, server.js, tests/integration/index.js, tests/integration/publication-patch.test.js
PATCH /readers/:readerId/publications/:pubId
Only needs the properties to be updated in the body of the request.
Returns the updated publication object.
=> patch publication endpoint working

routes/publication-delete-tag.js, routes/publication-post.js, routes/publication-put-tag.js, tests/integration/auth-error.test.js, tests/integration/publication-post.test.js, tests/integration/publication-tag.test.js, tests/utils/utils.js
This renames routes:
PUT and DELETE `/readers/:readerId/publications/:pubId/tags/:tagId` to `/publications/:pubId/tags/:tagId`
POST `/readers/:readerId/publications` to `/publications`
It also validates that the pubId and tagId belong to the reader, based on the token.
=> Rename routes and validate ownership

models/Tag.js, routes/tags-get.js, server.js, tests/integration/auth-error.test.js, tests/integration/index.js, tests/integration/tags-get.test.js, tests/models/Tag.test.js
This was surprisingly quick. 
So new endpoint: `/tags` 
returns the tags for a reader, based on the token. 
That's it.
I didn't write a ton of tests for it. Some things might change once I update the other tag endpoints and I might add more tests then. But there are not a lot of scenarios to test because this is so simple.
=> new endpoint: Get tags

models/Reader.js, models/Tag.js, tests/integration/deprecated/tag-delete-old.test.js, tests/integration/deprecated/tag-update.test.js, tests/integration/reader-create.test.js, tests/integration/tag/tag-delete.test.js, tests/integration/tag/tag-patch.test.js, tests/integration/tag/tags-get.test.js, tests/models/Tag.test.js
So I fixed it so that whenever a new Reader is created, we also create 4 tags for that reader for the 4 default 'modes'. 
Those tags are not returned with the Reader object when it is created, since the tags are not included there, but they will show up in the library tags and in the GET /tags endpoint.
=> Default modes

models/Note.js, routes/note-put.js, server.js, tests/integration/auth/forbidden.test.js, tests/integration/auth/unauthorized.test.js, tests/integration/index.js, tests/integration/note/note-get.test.js, tests/integration/note/note-put.test.js, tests/integration/readerNotes/readerNotes-orderBy.test.js
new endpoint: 
PUT /notes/:id
I also fixed the readerNotes orderBy updated filter. And also fixed the Get Note tests to use the new note model
=> Put note endpoint

models/NoteRelation.js, routes/noteRelation-post.js, routes/swagger-definitions/noteRelation-def.js, server.js, tests/integration/index.js, tests/integration/noteRelation/noteRelation-post.test.js
new endpoint:
POST /noteRelations
body:
```
{
from: <noteId>,
to: <noteId>,
type: <string>
previous: <noteRelationId>,
next: <noteRelationId>,
contextId: <noteRelationContextId>,
json: <object>
}
```
required properties:
- from
- type
Note that 'to' is not a required property, so you can create a relation with just one note. The reason why I did that is that the noteRelationContext will contain noteRelations, not notes. So if we want, for example, to add some unsorted notes to an outline, they have to have a noteRelation. 
Also note that previous / next are noteRelations, not notes
noteRelation can only have one context.
=> post noteRelations route

models/NoteRelation.js, routes/noteRelation-delete.js, routes/noteRelation-post.js, routes/noteRelation-put.js, server.js, tests/integration/auth/forbidden.test.js, tests/integration/auth/unauthorized.test.js, tests/integration/index.js, tests/integration/noteRelation/noteRelation-delete.test.js, tests/integration/noteRelation/noteRelation-post.test.js, tests/integration/noteRelation/noteRelation-put.test.js, tests/utils/testUtils.js
Two new endpoints:
PUT /noteRelations/:id
DELETE /noteRelations/:id
the delete is a soft delete.
Aside from that, works as expected.
I also added some validation for the PUT and POST endpoints to make sure that the notes and noteRelation ids passed to properties like 'from', 'to', 'previous', and 'next' point to object owned by the same reader. It would be weird if it ever came up, but better safe than sorry.
=> Put and delete note relation

models/Note.js, models/NoteBody.js, models/NoteContext.js, routes/note-put.js, routes/noteContext-addNote.js, routes/noteContext-delete.js, routes/noteContext-post.js, routes/noteContext-put.js, routes/swagger-definitions/noteContext-def.js, server.js, tests/integration/auth/forbidden.test.js, tests/integration/auth/unauthorized.test.js, tests/integration/index.js, tests/integration/noteContext/noteContext-addNote.test.js, tests/integration/noteContext/noteContext-delete.test.js, tests/integration/noteContext/noteContext-post.test.js, tests/integration/noteContext/noteContext-put.test.js, tests/models/NoteContext.test.js, tests/utils/testUtils.js
POST /noteContexts
PUT /noteContexts/:id
DELETE /noteContexts/:id
POST /noteContexts/:id/notes
The last one works like POST /notes but also assigns a contextId to the note. 
It is also possible to use it to copy an existing note into a context:
POST /noteContexts/:id/notes?source=noteId
In that case, you don't need to pass in a body (in fact, if you do, it will be ignored)
Also, the new note will have a 'original' property, which will be the id of the original note. 
Technically, it is also possible to create a note using POST /notes and pass in a note with a contextId. I'll have to check of the validation of the context works there too. But for now, it's safer to use the POST /noteContexts/:id/notes route.
=> Note context routes

models/readerNotes.js, tests/integration/readerNotes/readerNotes-get.test.js
so the route used to get notes for a user: GET /notes now only returns notes that are not context-specific. Notes that are created in a context, whether they are new notes or copies of existing notes, should not be in the notes page. 
Correct?
=> get readerNotes should not return notes with a contextId

migrations/20190409160623_note.js, models/Note.js, package-lock.json, package.json, routes/outline-get.js, server.js, tests/integration/index.js, tests/integration/outline/outline-get.test.js, tests/unit/outline-utils.test.js, tests/utils/testUtils.js, utils/outline.js
This includes 
- a function to convert a list of notes to a tree
- GET /outlines/:id endpoint
the outline will look just like the noteContext object, except that the notes property contains a tree of notes, where notes have a 'children' property.
the endpoint can only be used to get a noteContext with a type of 'outline'. If you try to fetch another noteContext, it will return a 404 error
=> Get Outline endpoint

models/readerNotes.js, tests/integration/readerNotes/readerNotes-get.test.js
GET /notes
will now return notes with a list of tags for each note
I also fixed is so that notes will by default be ordered by latest updated if no orderBy is specified. Until now, it was returning whatever default order the database returned, which could change from one time to another.
=> get notes with tags

models/library.js, routes/library-get.js, tests/integration/index.js, tests/integration/library/library-filter-combined.test.js, tests/integration/library/library-filter-search.test.js, tests/integration/library/library-orderBy-type.test.js
new query:
GET /library?orderBy=type    or /library?orderBy=type&reverse=true
also, the search query will now search through:
- name
- description
- abstract
- keywords
- NEW: attributions (all of them)
=> Library orderBy type, search by attribution

models/Note.js, models/NoteContext.js, routes/outline-addNote.js, routes/outline-delete.js, routes/outline-deleteNote.js, routes/outline-post.js, routes/outline-put.js, routes/swagger-definitions/noteContext-def.js, server.js, tests/integration/auth/forbidden.test.js, tests/integration/auth/unauthorized.test.js, tests/integration/index.js, tests/integration/outline/outline-addNote.test.js, tests/integration/outline/outline-deleteNote.test.js, tests/integration/outline/outline-get.test.js, tests/integration/outline/outline-post.test.js, tests/integration/outline/outline-put.test.js, tests/integration/outline/outlline-delete.test.js, tests/utils/testUtils.js, utils/outline.js
New endpoints:
POST /outlines
DELETE /outlines/:id 
currently a hard delete. Not sure why I did it that way. I could change that to a soft delete. 
PUT /outlines:id
add note to outline:
POST /outlines/:id/notes
optinally query: source=<noteId> to copy an existing note.
For new notes, it supports having a parentId, previous and/or next. It does not check that the position of the note makes sense. If it doesn't, you will find out when fetching the outline when you'll get an error. Not ideal, but doing those checks would be pretty complicated.
When copying an existing note, you can't give it a position because it wont use a body. I should however make sure that it deletes any position properties from that note if it has any. Right now it doesn't because it assumes that notes we copy in the …
=> Post, Delete, Put Outlines, add / remove notes from outline

routes/outline-patchNote.js, server.js, tests/integration/auth/forbidden.test.js, tests/integration/auth/unauthorized.test.js, tests/integration/index.js, tests/integration/outline/outline-patchNote.test.js, utils/outline.js
new endpoint:
PATCH /outlines/:outlineId/notes/:noteId
body of request should contain only the property of the notes that are being updated.
You can use it to update the position of a note (parentId, previous, next) and other notes will be updated to reflect the new order. 
Will not throw an error if the new position of the note does not make sense.
=> Update note in outline

models/Notebook.js, routes/notebook-get.js, routes/notebooks.get.js, routes/swagger-definitions/notebook-def.js, server.js, tests/integration/auth/forbidden.test.js, tests/integration/auth/unauthorized.test.js, tests/integration/index.js, tests/integration/notebook/notebook-get.test.js, tests/integration/notebook/notebooks-get.test.js, tests/models/Notebook.test.js, tests/utils/testUtils.js
Two endpoints:
GET /notebooks/:id
returns the notebook with:
- tags (tags assigned to the notebook)
- notebookTags (tags that are used to tag things within the notebook)
- publications
- notes
- noteContexts
GET /notebooks
returns all notebooks for a reader. Each notebook includes:
- tags (tags assigned to the notebook)
Is there anything else that should be included?
Eventually, the GET /notebooks endpoint should have filters (especially filter by status) and pagination.
=> Get notebook

models/Notebook_Pub.js, routes/notebooks/notebook-delete-pub.js, routes/notebooks/notebook-put-pub.js, server.js, tests/integration/auth/forbidden.test.js, tests/integration/auth/unauthorized.test.js, tests/integration/index.js, tests/integration/notebook/notebook-get.test.js, tests/integration/notebook/notebook-pub-delete.test.js, tests/integration/notebook/notebook-pub-put.test.js, tests/models/Notebook_Pub.test.js, tests/utils/testUtils.js
Two new endpoints:
PUT /notebooks/:id/publications/:pubId
DELETE /notebooks/:id/publications/:pubId
To add or remove a notebook-pub relation (which is a many-to-many relation)
Both endpoints take no body and return a 204 status.
=> Notebook pub

models/Note.js, models/ReadActivity.js, models/readerNotes.js, routes/_swagger-definitions/note-def.js, routes/_swagger-definitions/source-def.js, routes/sources/library-get.js, tests/integration/index.js, tests/integration/library/library-lastRead.test.js, tests/integration/note/note-get.test.js, tests/integration/readerNotes/readerNotes-filter-flag.test.js, tests/integration/readerNotes/readerNotes-filter-notebook.test.js, tests/models/ReadActivity.test.js, tests/utils/testUtils.js
Changes done for the dashboard:
/notes endpoint
- notes already included tags, but that was not tested or documented. I did that. Also with the /notes/:id endpoint.
- notes now include a 'notebooks' property. This will be a list of notebooks because the API accepts multiple notebooks for a note. Also did the change with the /notes/:id endpoint
/library endpoint
new query parameter: lastRead=<number>
If used, the response object will include a second list of sources under the 'lastRead' property with the sources with the latest read activity.
=> Dashboard changes

models/Reader.js, models/readerNotes.js, routes/notes/readerNotes-get.js, tests/integration/index.js, tests/integration/library/library-lastRead.test.js, tests/integration/reader/reader-post.test.js, tests/integration/readerNotes/readerNotes-filter-colour.test.js, tests/integration/readerNotes/readerNotes-filter-combined.test.js, tests/integration/tag/tag-delete.test.js, tests/integration/tag/tag-put.test.js, tests/integration/tag/tags-get.test.js, tests/models/Tag.test.js
the colour tags have been changed from type 'flag' to type 'colour'
I also added a colour filter to the notes endpoint:
GET /notes?colour=colour1
This works just like the flag filter. Accepted values are 'colour1', 'colour2', 'colour3', 'colour4'
I also removed the workspace tags.
=> Colour tags

models/readerNotes.js, routes/notes/readerNotes-get.js, tests/integration/index.js, tests/integration/readerNotes/readerNotes-filter-dateRangeUpdate.test.js
new filter:
GET /notes?updatedStart=<date>&updatedEnd=<date>
The filters can be used together or individually. They work just like publishedStart and publishedEnd.And they will throw an error if the start timestamp is after the end timestamp. 
Note that when you create a note, it saves a timestamp in both 'published' and 'updated' field.
=> filter notes by date updated

models/library.js, routes/sources/library-get.js, tests/integration/library/library-filter-collection.test.js, tests/integration/library/library-filter-tag.test.js
With the library endpoint, the 'tag' and 'stack' endpoints now accept multiple values.
For example:
GET /library?stack=stack1&stack=stack2
It will return sources that are in those two stacks.
=> library tag filters with multiple values

models/Note_Tag.js, models/library.js, models/readerNotes.js, tests/integration/library/library-filter-collection.test.js, tests/integration/reader/reader-delete.test.js, tests/integration/readerNotes/readerNotes-filter-source.test.js, tests/integration/tag/tag-post.test.js, tests/utils/testUtils.js
This cleans up the objects returned by the GET /library and GET /notes endpoints.
For example, the library returns the tags, as well as tags for each source. Those will no longer include a readerId, 'deleted' timestamp, etc. It shouldn't change anything for the front-end. If you worry that it does, I can clarify what exactly has been removed.
there is probably more that can be removed, but I will look at that more closely when I look at the overall design of the API
=> cleanup return objects

migrations/20200901101934_add_referenced_to_sources.js, models/Note.js, models/Notebook.js, models/Source.js, models/library.js, routes/sources/source-delete.js, routes/sources/source-get.js, tests/integration/note/note-get.test.js, tests/integration/readerNotes/readerNotes-get.test.js, tests/integration/source/source-delete.test.js, tests/models/Source.test.js
This adds an optional query parameter to the delete source route:
DELETE /sources/:id?reference=true
This will modify the source to add a 'referenced' timestamp and remove data that is stored in 'links', 'resources', 'readingOrder'
Eventually we should probably make it delete the actual content files (for normal deletes too, of course)
When you are getting the library,  'referenced' sources will not show up. You also cannot fetch them individually. However, when you get the notes (either individually or in the /notes endpoint), it will include the source information. 
In doing that, I noticed that we were not actually getting the source information when fetching the notes individually. That is fixed.
I also noticed that when a source is soft-deleted, its id will still show up in the …
=> Turning a source into a reference

models/Source.js, models/library.js, routes/_swagger-definitions/source-def.js, routes/sources/library-get.js, tests/integration/library/library-get.test.js, tests/integration/source/source-get.test.js
This adds 'lastReadActivity' to source objects retrieved with both those endpoints:
GET /sources/:id
GET /library
It only gives you one readActivity object.
=> Source with read activity

models/Notebook.js, tests/integration/notebook/notebook-get.test.js
So when you are fetching an individual notebook with GET /notebooks/{notebookId}
You will now get more information:
notebook.notes -> each note will have a .tags array and a .source property, if relevant.
notebook.sources -> each source will have a .tags array property
@cesarCSM was that everything?
=> notebook notes with source and tags, notebook sources with tags

models/Source.js, routes/notebooks/notebook-note-post.js, routes/notebooks/notebook-source-post.js, server.js, tests/integration/index.js, tests/integration/notebook/notebook-note-post.test.js, tests/integration/notebook/notebook-source-post.test.js
New route:
POST /notebooks/{notebookId}/sources
to create a source inside a notebook. This creates a source and creates a notebook_source relation.
By doing this, I also noticed that this route, and the POST /notebooks/{notebookId}/notes route, it wasn't possible to create a source or note with tags, like you can do with POST /sources and POST /notes. I fixed that.
=> Create source in notebook

models/Tag.js, tests/integration/note/note-post.test.js, tests/integration/notebook/notebook-note-post.test.js, tests/integration/notebook/notebook-source-post.test.js, tests/integration/source/source-post.test.js
For the following endpoints, used to create sources and notes:
POST /sources
POST /notes
POST /notebooks/:notebookId/sources
POST /notebooks/:notebookId/notes
You can create your sources or notes with tags. This was already working. What I am clarifying here is what happens when the tags you are giving your sources or notes are invalid.
In summary: invalid tags are ignored. They will not be created or assigned to the Source or Note. You will not get an error because the Source or Note is still created. 
More detailed explanation: for each tag in a .tags array:
If it has an id, I assume it exists and try to assign it to the Note/Source. If it doesn't exist, I ignore it.
If it doesn't have an id, I assume it doesn't exist and try to create it. If I get an error trying to create (for …
=> Handling invalid tags better when creating them with notes or sources

models/Source.js, routes/notebooks/notebook-delete-source.js, routes/notebooks/notebook-put-source.js, routes/sources/readActivity-post.js, routes/sources/source-delete-tag.js, routes/sources/source-delete.js, routes/sources/source-patch.js, routes/sources/source-post.js, routes/sources/source-put-tag.js, routes/tags/tag-delete.js, routes/tags/tag-post.js, routes/tags/tag-put.js, server.js, tests/integration/library/library-get.test.js
This fixes the library cache, which uses the 'If-Modified-Since' header and returns a 304 status if the library has not been modified since that date.
The library is reset when:
- a source is created (either by itself or within a notebook), updated or deleted
- a tag is created, updated or deleted
- a source is assigned to a tag or a source is removed from a tag
- a source is assigned to a notebook, or a source is removed from a notebook
- a readActivity is created
=> Fix library cache

migrations/20200925095735_add-noteBody-formattedContent.js, models/Note.js, models/NoteBody.js, models/readerNotes.js, package-lock.json, package.json, tests/integration/readerNotes/readerNotes-filter-search.test.js
This fixes the notes search so that it ignores the html tags. To do this, I had to add an extra column in the notebody table, which stores the cleaned up content. This html-free content will not be returned by the API anywhere, it is only there for searching purposes.
That also means another new migration. Fun! 
The migration does not modify any of the existing notes, so any notes that are currently in the database will not be returned when we do a search.
=> make search ignore html tags

models/Notebook.js, models/Notebook_Note.js, routes/notes/note-post.js, routes/notes/note-put.js, tests/integration/note/note-post.test.js, tests/integration/note/note-put.test.js
This feature works the same as creating or updating notes with tags.
So now with endpoints: `POST /notes` and `PUT /notes/:id` the notes object can have a 'notebooks' property, which will be an array of notebook objects. Any notebook objects that has an id will be assumed to already exist and will be assigned to the note. Any notebook without an id will be created and then assigned to the note.
If the note already had notebooks, the list you pass in will replace the existing notebook assignments. So if you pass in an empty array, that will remove the note from any notebooks it was in.
If you don't have a notebooks property, nothing will happen to any existing notebook assignments.
In any cases, if there are errors with the notebooks (for example if you try to create a new notebook without …
=> Create and update note with notebooks

models/Notebook.js, tests/integration/notebook/notebook-get.test.js
Change to GET /notebooks/:id
the notebook object already had a .sources array. Those sources now include their attributions, including an author array.
=> add author to notebook source

models/Source.js, tests/integration/source/source-patch.test.js
I was able to reproduce the bug and fix it. 
It was happening when a source had nothing stored in the 'metadata' json object and then we tried to update to put some in.
=> Fixed the metadata bug

models/Source.js, routes/hardDelete.js, tests/integration/hardDelete/deletePub.test.js, tests/models/Source.test.js
I did that before the emptied notes thing, but somehow forgot to create a pull request.
So we already had a parameter reference=true
Now when we use that parameter, the source will be marked as 'referenced'. When the hard delete, we remove this information from the source:
- links
- resources
- readingOrder
We will probably want to delete more. TBD.
=> hard delete for referenced sources

migrations/20201026104557_add_emptied_to_notes.js, models/Note.js, models/NoteContext.js, models/Notebook.js, models/Source.js, models/readerNotes.js, routes/hardDelete.js, routes/notes/note-delete.js, tests/integration/hardDelete/deleteNote.test.js, tests/integration/note/note-delete.test.js, tests/models/Note.test.js, tests/models/Source.test.js
Added a parameter to the delete note endpoint
DELETE /notes/:id?empty=true
Emptied notes will not be returned on those endpoints:
GET /notes/:id
GET /notes
It will also not show up when getting an individual source or notebook.
It is only returned when getting an individual NoteContext
When we run the hard delete, we will delete the Note's:
- json
- stylesheet
- canonical
- target
- document
- body (which contains both the motivation and content)
I do not delete the:
sourceId
contextId
and all the outline information.
The contextId and outline information are still needed to know where to put the empty note card.
The sourceId could be deleted, but knex/objection have this weird bug/feature where you can't update a foreign key to null.
=> emptied notes

models/readerNotes.js, routes/notes/readerNotes-get.js, tests/integration/index.js, tests/integration/readerNotes/readerNotes-filter-combined.test.js, tests/integration/readerNotes/readerNotes-filter-notMotivation.test.js
Adding a filter for the GET /notes endpoint: notMotivation
It works just like the motivation filter, but it excludes notes by motivation. It can be combined with pagination and other filters, except for the motivation filter, obviously.
It only takes one value. If you need it to accept more than one, let me know and I can fix that.
=> notes filter by notMotivation

models/Note.js, models/Tag.js, tests/integration/note/note-delete.test.js, tests/integration/note/note-put.test.js, tests/integration/tag/tag-put.test.js, utils/utils.js
This fixes the bug that was preventing us from updating a foreign key to null.
We can now do this update on Note.contextId, Note.sourceId and Tag.notebookId
Most other foreign keys are required, so no need to update them to null. 
Let me know if there are any other cases that you can think of. Normally they should work, but I can add a test to make sure they do.
=> fixed it so we can update foreign keys to null

models/NoteContext.js, tests/integration/outline/outline-get.test.js
so when you request an outline, or another noteContext, you get a list of notes. With this pull request, each note in this list will have:
note.tags
note.source (with only the name and id of the source)
=> outline with note tags and source name

models/Note.js, routes/outlines/outline-addNote.js, tests/integration/outline/outline-addNote.test.js
With this change, when we copy an existing note to an outline, we can also pass in a body with modifications to the note.
for example:
POST /outlines/:id/notes?source=noteId
with body { next: note2, previous: note3 }
=> add note to outline with modifications

models/Note.js, models/Note_Tag.js, routes/outlines/outline-addNote.js, tests/integration/outline/outline-addNote.test.js
fixing it so that when you copy a note and give it a previous or next property, it will make the adjustments to surrounding notes in the outline.
Also, fixing it so that the copied note will have the same tags as the original. 
Note: will merge this shortly so that I can deploy.
=> fix outline bug and keep tags on copied notes

models/Collaborator.js, routes/_swagger-definitions/collaborator-def.js, routes/collaborator/collaborator-delete.js, routes/collaborator/collaborator-post.js, routes/collaborator/collaborator-put.js, server.js, tests/integration/auth/collaboration-auth.test.js, tests/integration/collaborator/collaborator-delete.test.js, tests/integration/collaborator/collaborator-post.test.js, tests/integration/collaborator/collaborator-put.test.js, tests/integration/index.js, tests/models/Collaborator.test.js, tests/utils/testUtils.js
Creating three routes:
POST /notebooks/:notebookId/collaborators
PUT /notebooks/:notebookId/collaborators/:collaboratorId
DELETE /notebooks/:notebookId/collaborators/:collaboratorId
For now:
- only the owner of the notebook can create a collaborator. Eventually, some collaborators might be able to as well (that might depend on their level of permission)
- the collaborator can update or delete the collaborator object. Eventually the owner will too. Maybe other collaborators too, depending on permission level?
Aside from that, it is all pretty straightforward.
=> Collaborator routes

models/Collaborator.js, models/Note.js, models/NoteContext.js, models/Notebook.js, models/Source.js, package.json, routes/noteContexts/noteContext-get.js, routes/notebooks/notebook-get.js, routes/notes/note-get.js, routes/outlines/outline-get.js, routes/sources/source-get.js, tests/integration/auth/collaboration-auth.test.js, tests/integration/collaboration/collaboration-note-get.test.js, tests/integration/collaboration/collaboration-noteContext-get.test.js, tests/integration/collaboration/collaboration-notebook-get.test.js, tests/integration/collaboration/collaboration-source-get.test.js, tests/integration/index.js, tests/unit/utils.test.js, utils/utils.js
Collaborator access on those routes:
GET /notebooks/:id
GET /sources/:id (if source is part of a shared notebook)
GET /notes/:id (if note is part of a shared notebook, or in a noteContext or outline belonging to a shared notebook)
GET /noteContexts/:id
GET /outlines/:id
The collaborator must have a status of 'accepted' and a permission.read = true
=> Get stuff as a collaborator

routes/noteContexts/noteContext-addNote.js, routes/notebooks/notebook-note-post.js, routes/outlines/outline-addNote.js, tests/integration/auth/collaboration-auth.test.js, tests/integration/collaboration/collaboration-noteContext-note-post.test.js, tests/integration/collaboration/collaboration-notebook-note-post.test.js, tests/integration/collaboration/collaboration-outline-note-post.test.js, tests/integration/index.js, tests/unit/outline-utils.test.js
Allows collaborators to create notes using those routes:
POST /notebooks/:id/notes
POST /noteContexts/:id/notes
POST /outlines/:id/notes
In all cases, the collaborator must have a status of 'accepted' and a permission.comment = true
In the case of outlines, I assume comments will not be part of the hierarchy of the outline, but they will just be in the same list, at the top level, with no children notes. People in the front-end might want to think about using a specific motivation type for the comments to differentiate them from the notes that are in the outline.
=> Create note as collaborator

models/Collaborator.js, models/Notebook.js, routes/notebooks/notebooks.get.js, tests/integration/collaboration/collaboration-notebooks-get.test.js, tests/integration/index.js, tests/utils/testUtils.js
Fixing it so that the GET /notebooks endpoints can return notebooks that the user is a collaborator on. 
This is optional, and you need to use a query parameter: GET /notebooks?collaboration=true
I did it that way because I had to make a second database query to get the collaboration notebooks, and I didn't want to slow everything down for something that is not even used yet. 
I might be able to consolidate into a single query, but I am not sure. I will take another look when we start using it. If that works, I will remove the query parameter.
=> Get notebooks as collab

models/Note.js, models/Notebook.js, models/Notebook_Note.js, models/Notebook_Source.js, models/Notebook_Tag.js, routes/outlines/outline-patchNote.js, server.js, tests/integration/notebook/notebook-delete.test.js, tests/integration/outline/outline-patchNote.test.js
Fixing: 
- the bugs related with deleting notebooks (when deleting a notebook, it will also delete any related notebook_note, notebook_source and notebook_tag relation)
- fix it so that when trying to access a route that does not exist, user will get a 404 error object instead of an html page
- fix problem of switching notes in an outline that is one list of two notes
=> Delete notebook bug

models/Source.js, routes/sources/library-get.js, tests/integration/library/library-get.test.js, tests/integration/source/source-get.test.js, tests/integration/source/source-patch.test.js, tests/integration/source/source-post.test.js
Doesn't change the database. 
Now you can create / update sources with properties:
- pagination (string, something like '100-110')
- isPartOf (object)
- title (title of journal)
- datePublished (date)
- issueNumber (string)
- volumeNumber (string)
That information is also returned on endpoints:
GET /sources/:id
GET /library
=> Article metadata

.github/workflows/CI.yml, deployments-dev.md, guides/development.md, knexfile.js, tests/google-integration/index.js, tests/integration/index.js, tests/models/index.js
Using a database cluster on Digital Ocean requires a custom `PORT` and an SSL connection. Rather than adding another configuration for this, a connection string provides more flexibility and reduces database configuration down to one parameter.
=> Use a connection string for database

deployments-dev.md, knexfile.js
Only if the environment variable is configured. This is required for deployment environments such as Digital Ocean.
=> Configure the DB connection with CA certificate
